use fluxdown_ui_i18n::{Translator, keys};
use gpui::SharedString;

use crate::view::SettingsCategory;

#[derive(Clone)]
pub(crate) struct SettingsStrings {
    pub(crate) add_category: SharedString,
    pub(crate) analytics_enabled: SharedString,
    pub(crate) analytics_enabled_desc: SharedString,
    pub(crate) auto_category_dirs: SharedString,
    pub(crate) auto_startup: SharedString,
    pub(crate) auto_startup_desc: SharedString,
    pub(crate) builtin_category: SharedString,
    pub(crate) category_about: SharedString,
    pub(crate) category_about_desc: SharedString,
    pub(crate) category_account: SharedString,
    pub(crate) category_account_desc: SharedString,
    pub(crate) category_all: SharedString,
    pub(crate) category_api: SharedString,
    pub(crate) category_api_desc: SharedString,
    pub(crate) category_appearance: SharedString,
    pub(crate) category_appearance_desc: SharedString,
    pub(crate) category_audio: SharedString,
    pub(crate) category_bt: SharedString,
    pub(crate) category_bt_desc: SharedString,
    pub(crate) category_doctor: SharedString,
    pub(crate) category_doctor_desc: SharedString,
    pub(crate) category_document: SharedString,
    pub(crate) category_download: SharedString,
    pub(crate) category_download_desc: SharedString,
    pub(crate) category_ed2k: SharedString,
    pub(crate) category_ed2k_desc: SharedString,
    pub(crate) category_extensions: SharedString,
    pub(crate) category_extensions_desc: SharedString,
    pub(crate) category_general: SharedString,
    pub(crate) category_general_desc: SharedString,
    pub(crate) category_notify: SharedString,
    pub(crate) category_notify_desc: SharedString,
    pub(crate) category_priority_note: SharedString,
    pub(crate) category_proxy: SharedString,
    pub(crate) category_proxy_desc: SharedString,
    pub(crate) category_video: SharedString,
    pub(crate) close_to_tray: SharedString,
    pub(crate) close_to_tray_desc: SharedString,
    pub(crate) custom_categories: SharedString,
    pub(crate) ed2k_link_association: SharedString,
    pub(crate) ed2k_link_association_desc: SharedString,
    pub(crate) floating_ball: SharedString,
    pub(crate) floating_ball_desc: SharedString,
    pub(crate) group_startup_tray: SharedString,
    pub(crate) group_system: SharedString,
    pub(crate) keep_awake: SharedString,
    pub(crate) keep_awake_desc: SharedString,
    pub(crate) language: SharedString,
    pub(crate) language_chinese: SharedString,
    pub(crate) language_desc: SharedString,
    pub(crate) language_english: SharedString,
    pub(crate) magnet_association: SharedString,
    pub(crate) magnet_association_desc: SharedString,
    pub(crate) reset_categories: SharedString,
    pub(crate) search_hint: SharedString,
    pub(crate) show_titlebar_pause: SharedString,
    pub(crate) show_titlebar_pause_desc: SharedString,
    pub(crate) show_titlebar_resume: SharedString,
    pub(crate) show_titlebar_resume_desc: SharedString,
    pub(crate) show_titlebar_settings: SharedString,
    pub(crate) show_titlebar_settings_desc: SharedString,
    pub(crate) show_titlebar_theme: SharedString,
    pub(crate) show_titlebar_theme_desc: SharedString,
    pub(crate) start_minimized: SharedString,
    pub(crate) start_minimized_desc: SharedString,
    pub(crate) theme_mode: SharedString,
    pub(crate) theme_mode_dark: SharedString,
    pub(crate) theme_mode_desc: SharedString,
    pub(crate) theme_mode_light: SharedString,
    pub(crate) titlebar_buttons: SharedString,
    pub(crate) titlebar_buttons_desc: SharedString,
    pub(crate) torrent_association: SharedString,
    pub(crate) torrent_association_desc: SharedString,
}

impl SettingsStrings {
    pub(crate) fn from_translator(translator: &Translator) -> Self {
        Self {
            add_category: text(translator, "addCategory"),
            analytics_enabled: text(translator, "analyticsEnabled"),
            analytics_enabled_desc: text(translator, "analyticsEnabledDesc"),
            auto_category_dirs: text(translator, "autoCategoryDirs"),
            auto_startup: text(translator, "autoStartup"),
            auto_startup_desc: text(translator, "autoStartupDesc"),
            builtin_category: text(translator, "builtinCategory"),
            category_about: text(translator, "settingsCatAbout"),
            category_about_desc: text(translator, "settingsCatAboutDesc"),
            category_account: text(translator, "settingsCatAccount"),
            category_account_desc: text(translator, "settingsCatAccountDesc"),
            category_all: text(translator, keys::CATEGORY_ALL),
            category_api: text(translator, "settingsCatApiService"),
            category_api_desc: text(translator, "settingsCatApiServiceDesc"),
            category_appearance: text(translator, keys::SETTINGS_CAT_APPEARANCE),
            category_appearance_desc: text(translator, "settingsCatAppearanceDesc"),
            category_audio: text(translator, keys::CATEGORY_AUDIO),
            category_bt: text(translator, "settingsCatBt"),
            category_bt_desc: text(translator, "settingsCatBtDesc"),
            category_doctor: text(translator, "settingsCatDoctor"),
            category_doctor_desc: text(translator, "settingsCatDoctorDesc"),
            category_document: text(translator, keys::CATEGORY_DOCUMENT),
            category_download: text(translator, "settingsCatDownload"),
            category_download_desc: text(translator, "settingsCatDownloadDesc"),
            category_ed2k: text(translator, "settingsCatEd2k"),
            category_ed2k_desc: text(translator, "settingsCatEd2kDesc"),
            category_extensions: text(translator, "settingsCatExtensions"),
            category_extensions_desc: text(translator, "settingsCatExtensionsDesc"),
            category_general: text(translator, "settingsCatGeneral"),
            category_general_desc: text(translator, "settingsCatGeneralDesc"),
            category_notify: text(translator, "settingsCatNotify"),
            category_notify_desc: text(translator, "settingsCatNotifyDesc"),
            category_priority_note: text(translator, "categoryPriorityNote"),
            category_proxy: text(translator, "settingsCatProxy"),
            category_proxy_desc: text(translator, "settingsCatProxyDesc"),
            category_video: text(translator, keys::CATEGORY_VIDEO),
            close_to_tray: text(translator, "closeToTray"),
            close_to_tray_desc: text(translator, "closeToTrayDesc"),
            custom_categories: text(translator, "customCategories"),
            ed2k_link_association: text(translator, "ed2kLinkAssociation"),
            ed2k_link_association_desc: text(translator, "ed2kLinkAssociationDesc"),
            floating_ball: text(translator, "floatingBall"),
            floating_ball_desc: text(translator, "floatingBallDesc"),
            group_startup_tray: text(translator, "settingsGroupStartupTray"),
            group_system: text(translator, "settingsGroupSystem"),
            keep_awake: text(translator, "keepAwakeWhileDownloading"),
            keep_awake_desc: text(translator, "keepAwakeWhileDownloadingDesc"),
            language: text(translator, keys::LANGUAGE),
            language_chinese: text(translator, keys::LANGUAGE_CHINESE),
            language_desc: text(translator, keys::LANGUAGE_DESC),
            language_english: text(translator, keys::LANGUAGE_ENGLISH),
            magnet_association: text(translator, "magnetLinkAssociation"),
            magnet_association_desc: text(translator, "magnetLinkAssociationDesc"),
            reset_categories: text(translator, "resetBuiltinCategories"),
            search_hint: text(translator, "settingsSearchHint"),
            show_titlebar_pause: text(translator, "showTitlebarPauseAll"),
            show_titlebar_pause_desc: text(translator, "showTitlebarPauseAllDesc"),
            show_titlebar_resume: text(translator, "showTitlebarResumeAll"),
            show_titlebar_resume_desc: text(translator, "showTitlebarResumeAllDesc"),
            show_titlebar_settings: text(translator, "showTitlebarSettings"),
            show_titlebar_settings_desc: text(translator, "showTitlebarSettingsDesc"),
            show_titlebar_theme: text(translator, "showTitlebarTheme"),
            show_titlebar_theme_desc: text(translator, "showTitlebarThemeDesc"),
            start_minimized: text(translator, "startMinimizedToTray"),
            start_minimized_desc: text(translator, "startMinimizedToTrayDesc"),
            theme_mode: text(translator, keys::THEME_MODE),
            theme_mode_dark: text(translator, keys::THEME_MODE_DARK),
            theme_mode_desc: text(translator, keys::THEME_MODE_DESC),
            theme_mode_light: text(translator, keys::THEME_MODE_LIGHT),
            titlebar_buttons: text(translator, "titlebarButtons"),
            titlebar_buttons_desc: text(translator, "titlebarButtonsDesc"),
            torrent_association: text(translator, "torrentFileAssociation"),
            torrent_association_desc: text(translator, "torrentFileAssociationDesc"),
        }
    }

    pub(crate) fn category_label(&self, category: SettingsCategory) -> SharedString {
        match category {
            SettingsCategory::General => self.category_general.clone(),
            SettingsCategory::Account => self.category_account.clone(),
            SettingsCategory::Appearance => self.category_appearance.clone(),
            SettingsCategory::Download => self.category_download.clone(),
            SettingsCategory::BitTorrent => self.category_bt.clone(),
            SettingsCategory::Ed2k => self.category_ed2k.clone(),
            SettingsCategory::Proxy => self.category_proxy.clone(),
            SettingsCategory::ApiService => self.category_api.clone(),
            SettingsCategory::Notify => self.category_notify.clone(),
            SettingsCategory::Extensions => self.category_extensions.clone(),
            SettingsCategory::Doctor => self.category_doctor.clone(),
            SettingsCategory::About => self.category_about.clone(),
        }
    }

    pub(crate) fn category_description(&self, category: SettingsCategory) -> SharedString {
        match category {
            SettingsCategory::General => self.category_general_desc.clone(),
            SettingsCategory::Account => self.category_account_desc.clone(),
            SettingsCategory::Appearance => self.category_appearance_desc.clone(),
            SettingsCategory::Download => self.category_download_desc.clone(),
            SettingsCategory::BitTorrent => self.category_bt_desc.clone(),
            SettingsCategory::Ed2k => self.category_ed2k_desc.clone(),
            SettingsCategory::Proxy => self.category_proxy_desc.clone(),
            SettingsCategory::ApiService => self.category_api_desc.clone(),
            SettingsCategory::Notify => self.category_notify_desc.clone(),
            SettingsCategory::Extensions => self.category_extensions_desc.clone(),
            SettingsCategory::Doctor => self.category_doctor_desc.clone(),
            SettingsCategory::About => self.category_about_desc.clone(),
        }
    }
}

fn text(translator: &Translator, key: &str) -> SharedString {
    SharedString::from(translator.text(key).to_owned())
}
