/**
 * English translations
 */
import type { MessageKey } from "./zh-CN";

const en: Record<MessageKey, string> = {
  // Header
  "header.themeToggle": "Toggle theme",
  "header.checking": "Checking...",
  "header.connected": "Connected",
  "header.disconnected": "Disconnected",

  // Main switch
  "switch.label": "Download Intercept",
  "switch.enabled": "Enabled",
  "switch.disabled": "Disabled",

  // Stats
  "stats.title": "Today's Stats",
  "stats.sent": "Downloaded",
  "stats.failed": "Failed",
  "stats.reset": "Reset Stats",
  "stats.resetDone": "Stats reset",

  // Quick settings
  "settings.title": "Quick Settings",
  "settings.interceptMode": "Intercept Mode",
  "settings.modeSmart": "Smart",
  "settings.modeAll": "Intercept All",
  "settings.hintSmart": "Smart detection based on filename, type, and size",
  "settings.hintAll": "Intercept all downloads (except excluded domains)",
  "settings.minFileSize": "Min File Size",
  "settings.sizeNoLimit": "No limit",
  "settings.interceptMagnet": "Take Over Magnet Links",
  "settings.interceptMagnetHint":
    "When off, magnet links go to the system default handler (e.g. qBittorrent)",
  "settings.altClickHint": "Alt+Shift+D toggles interception",
  "settings.dotVisible": "Floating Ball",

  // Remote download source
  "remote.title": "Remote Download Source",
  "remote.mode": "Mode",
  "remote.modeOff": "Desktop Only",
  "remote.modeFallback": "Desktop First",
  "remote.modeAlways": "Remote Only",
  "remote.modeHintOff": "Send downloads to the desktop app via Native Messaging only",
  "remote.modeHintFallback":
    "Prefer the desktop app; deliver to the remote server when it's unreachable",
  "remote.modeHintAlways":
    "Always deliver downloads to the remote server, skip the desktop app",
  "remote.serverUrl": "Server Address",
  "remote.serverUrlPlaceholder": "e.g. http://192.168.1.10:17800",
  "remote.token": "Access Token",
  "remote.tokenPlaceholder": "Enter access token",
  "remote.testConnection": "Test Connection",
  "remote.testing": "Testing...",
  "remote.testSuccess": "Connected ({app} v{version})",
  "remote.testAuthFailed": "Authentication failed, check the access token",
  "remote.testUnreachable":
    "Cannot reach the server, check the address and network",
  "remote.testNotConfigured": "Enter the server address first",
  "remote.testFailed": "Connection test failed: {message}",
  "remote.verifyRequired":
    "Remote modes unlock after the connection test passes on the settings page",
  "remote.openOptions": "Configure Server",

  // Options page
  "options.title": "FluxDown Settings",
  "options.remoteDesc":
    "Configure the fluxdown_server address and access token. Remote modes unlock after the connection test passes.",
  "options.verifiedState": "Status: connection verified",
  "options.unverifiedState": "Status: not verified (remote modes unavailable)",
  "options.navSettings": "Settings",
  "options.nav.general": "General",
  "options.nav.remote": "Remote Server",
  "options.general.languageTitle": "Interface Language",
  "options.general.languageDesc":
    "Choose the extension UI language, independent of the browser language",
  "options.general.languageAuto": "Auto (follow browser)",
  "options.general.themeTitle": "Appearance",
  "options.general.themeDesc": "Theme of the extension UI",
  "options.theme.system": "Follow System",
  "options.theme.light": "Light",
  "options.theme.dark": "Dark",
  "options.tokenDesc": "Management token generated by the server on first start",
  "footer.settings": "All Settings",

  // Task send notification toggles
  "options.general.notifyLocalTitle": "Local Task Notifications",
  "options.general.notifyLocalDesc":
    "Show a desktop notification when a task is sent to the local desktop app (created / failed)",
  "options.general.notifyRemoteTitle": "Remote Task Notifications",
  "options.general.notifyRemoteDesc":
    "Show a desktop notification when a task is sent to the remote server (created / failed)",

  // Intercept rules
  "options.nav.rules": "Intercept Rules",
  "options.rules.extTitle": "File Extensions",
  "options.rules.extDesc":
    "Downloads matching these extensions are intercepted (positive match in Smart mode). Add your own below; built-in entries cannot be removed",
  "options.rules.extPlaceholder": "e.g. .epub",
  "options.rules.add": "Add",
  "options.rules.builtinExts": "Built-in extensions",
  "options.rules.extEmpty": "No custom extensions yet",
  "options.rules.extInvalid": "Invalid format, e.g. .epub",
  "options.rules.extExists": "{ext} is already in the list",
  "options.rules.extAdded": "Added {ext}",
  "options.rules.mimeTitle": "MIME Types",
  "options.rules.mimeDesc":
    "Responses matching these MIME types are intercepted in Smart mode. A trailing slash matches the whole family (e.g. video/)",
  "options.rules.mimePlaceholder": "e.g. application/epub+zip or video/",
  "options.rules.mimeInvalid":
    "Invalid format, e.g. application/epub+zip or video/",
  "options.rules.resetMime": "Restore Defaults",
  "options.rules.mimeResetDone": "Default MIME list restored",


  // Domain exclusion
  "domain.title": "Excluded Domains",
  "domain.addTitle": "Add domain manually",
  "domain.add": "Add",
  "domain.cancel": "Cancel",
  "domain.placeholder": "Enter domain, e.g. example.com",
  "domain.currentSite": "Current Site",
  "domain.empty": "No excluded domains",
  "domain.removed": "Removed {domain}",
  "domain.exists": "{domain} already in exclusion list",
  "domain.excluded": "Excluded {domain}",
  "domain.cannotGetDomain": "Cannot get current page domain",
  "domain.excludeCurrent": "Exclude Current Site",

  // Notifications
  "notify.batchNoLinks": "No Links Found",
  "notify.batchNoLinksDetail": "No links found on this page",
  "notify.batchNoDownloadableLinks":
    "No downloadable file links found on this page",
  "notify.batchComplete": "Batch Download Complete",
  "notify.batchResult": "{total} files total, {sent} sent, {failed} failed",
  "notify.batchExtractFailed":
    "Failed to extract page links, check page permissions",
  "notify.downloadSent": "Download Sent",
  "notify.sentToFluxDown": "{name} sent to FluxDown",
  "notify.batchSentDetail": "{count} tasks sent to FluxDown",
  "notify.sendFailed": "Send Failed",
  "notify.connectionFailed": "Cannot connect to FluxDown app: {message}",
  "notify.fallbackBrowser": "Fell back to browser download",
  "notify.fallbackBrowserDetail":
    "Could not send to FluxDown, fell back to browser: {url}",
  "notify.appUnavailable": "FluxDown app not detected",
  "notify.appUnavailableDetail":
    "Temporarily using the browser's built-in download. Make sure the FluxDown desktop app is running; interception will resume automatically.",

  // Resource sniffer & panel
  "sniffer.title": "Resource Sniffer",
  "sniffer.resourceSniffing": "Resource Sniffing",
  "sniffer.resourceSniffingHint":
    "Detect downloadable resources; turning it off hides in-page buttons (reload after re-enabling)",
  "sniffer.showFloatingButton": "Video Float Button",
  "sniffer.showFloatingButtonHint":
    "Show quick download button on video elements",
  "sniffer.showResourcePanel": "Resource Panel",
  "sniffer.showResourcePanelHint":
    "Show detected resources panel at page bottom",
  "sniffer.sniffImages": "Image Sniffing",
  "sniffer.sniffImagesHint": "Detect large images on web pages (>100KB)",

  // Resource panel (content script)
  "panel.selectAll": "Select All",
  "panel.batchDownload": "Download",
  "panel.resources": "resources",
  "panel.empty": "No downloadable resources detected",
  "panel.collapse": "Collapse",
  "panel.more": "{count} more",
  "panel.hideDot": "Hide dot",
  "panel.download": "Download",
  "panel.floatDL": "DL",
  "panel.tabAll": "All",
  "panel.tabVideo": "Video",
  "panel.tabAudio": "Audio",
  "panel.tabDocs": "Docs",
  "panel.tabArchive": "Archive",
  "panel.tabStream": "Stream",
  "panel.tabSubtitle": "Subtitle",
  "panel.tabMagnet": "Magnet",
  "panel.tabOther": "Other",
  "panel.qualityPickerTitle": "Select Quality",
  "panel.trackVideo": "Video Track",
  "panel.trackAudio": "Audio Track",
  "panel.qualityUnknown": "Unknown Quality",
  "panel.previewTitle": "Preview",
  "panel.previewClose": "Close preview",
  "panel.previewFailed": "Preview failed to load, may require login or be blocked by CORS",
  "panel.previewUnsupported": "Preview not supported for this type",
  "panel.previewFragmentUnsupported": "This fragment can't be previewed on its own; merge it first",
  "panel.previewHlsUnsupported": "This browser can't play HLS directly. View it on the source page or open it with a player after downloading",
  "panel.previewDashUnsupported": "This browser can't play this DASH stream directly. View it on the source page or open it with a player after downloading",
  "panel.previewLimited": "Preview limited",
  "panel.previewLimitedHint": "Browser preview failed due to CORS/login limits, but download may still succeed (the engine sends your session)",
  "panel.clearFailed": "Clear failed previews",
  "panel.clearFailedHint": "Hide resources that failed to preview (doesn't affect others, and doesn't mean they can't be downloaded)",

  // Shortcut toggle
  "shortcut.toggleTitle": "Intercept Toggle",
  "shortcut.interceptOn": "Download interception enabled",
  "shortcut.interceptOff": "Download interception disabled",

  // Context menu
  "contextMenu.sendToFluxDown": "Download this link with FluxDown",
  "contextMenu.sendImageToFluxDown": "Download this image with FluxDown",
  "contextMenu.sendVideoToFluxDown": "Download this video/audio with FluxDown",
  "contextMenu.sendPageToFluxDown": "Download this page with FluxDown",

  // Manifest
  "manifest.description":
    "Intercept browser downloads and send to FluxDown app for high-speed downloading",

  // Top tabs (popup)
  "popup.tabs.tasks": "Tasks",
  "popup.tabs.resources": "Resources",
  "popup.tabs.settings": "Settings",

  // Resource panel (popup)
  "popup.resources.empty": "No resources sniffed on this page",

  // Task panel (popup)
  "popup.tasks.downloading": "Downloading",
  "popup.tasks.completed": "Recently Completed",
  "popup.tasks.empty": "No download tasks",
  "popup.tasks.appNotRunning": "FluxDown is not running",
  "popup.tasks.startApp": "Start FluxDown",
  "popup.tasks.starting": "Starting…",
  "popup.tasks.statsToday": "Today:",
  "popup.tasks.statsLineTitle": "Open settings for details",
  "popup.task.pause": "Pause",
  "popup.task.resume": "Resume",
  "popup.task.remove": "Remove",
  "popup.task.open": "Open",
  "popup.task.reveal": "Show in Folder",
  "popup.task.paused": "Paused",
  "popup.task.pending": "Pending",
  "popup.task.preparing": "Preparing",
  "popup.task.errorGeneric": "Download failed",
  "popup.task.opFailed": "Operation failed",

  // Quick download in empty state (popup)
  "popup.quickDownload.placeholder": "Paste a download URL",
  "popup.quickDownload.button": "Download",
  "popup.quickDownload.invalidUrl": "Enter a valid download URL",
  "popup.quickDownload.sent": "Sent to FluxDown",
  "popup.quickDownload.failed": "Send failed",

  // Options migration extras
  "options.general.statsDesc": "Reset the downloaded/failed counters shown in the popup",
  "options.rules.minFileSizeDesc": "Files smaller than this are not intercepted",
  "options.rules.domainDesc": "Downloads from these domains are never intercepted",

  // Custom protocol (fluxdown://)
  "options.protocol.label": "FluxDown Protocol",
  "options.protocol.enabled": "On — launch app via fluxdown://",
  "options.protocol.disabled": "Off (default)",
  "options.protocol.desc": "Launch the app via the fluxdown:// protocol — supported on Windows, macOS, Linux and Android. The native channel is more capable, so enable this only when it is unavailable",

  // Task completion notification (task panel)
  "notify.taskCompletedTitle": "Download Complete",
  "notify.taskCompletedDetail": "{name} has finished downloading",
  "notify.openFile": "Open File",
  "notify.openFolder": "Open Folder",
};

export default en;
