//! 构建期把 Web SPA 产物嵌入服务器二进制，实现单文件分发（下载即运行，
//! 不再需要同级 `web/` 目录）。
//!
//! 资源目录：`FLUXDOWN_EMBED_WEBROOT` 覆盖，缺省仓库内 `web/dist`。目录缺失或
//! 为空**不是错误**——本地 `cargo run -p fluxdown_agent --features web-ui` 不必先构建前端，生成
//! 空表即可，运行期由 `web_assets` 给出「未嵌入」提示页（或走 `FLUXDOWN_WEBROOT`
//! 磁盘目录）。
//!
//! 产物 `$OUT_DIR/web_assets.rs` 只含 `include_bytes!` 引用（字节由 rustc 直接
//! 读入 .rodata），不内联字面量：生成文件恒为几 KB，且 rustc 自动把被 include
//! 的文件记进 dep-info，前端产物一变就重编。ETag/Content-Type 在本脚本算，故
//! 每个文件都登记 `rerun-if-changed`。

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-env-changed=FLUXDOWN_EMBED_WEBROOT");
    println!("cargo::rerun-if-env-changed=CARGO_FEATURE_WEB_UI");

    // 未启用 `web-ui` 时 `web_assets` 模块不参与编译，无需扫描前端产物。
    if std::env::var_os("CARGO_FEATURE_WEB_UI").is_none() {
        return;
    }

    let manifest_dir = match std::env::var_os("CARGO_MANIFEST_DIR") {
        Some(v) => PathBuf::from(v),
        None => panic!("CARGO_MANIFEST_DIR not set by cargo"),
    };
    let out_dir = match std::env::var_os("OUT_DIR") {
        Some(v) => PathBuf::from(v),
        None => panic!("OUT_DIR not set by cargo"),
    };

    // 相对路径按包根解析（构建脚本的 cwd 即包根，但 include_bytes! 相对 OUT_DIR
    // 里的生成文件解析，故一律转绝对）。
    let webroot = match std::env::var_os("FLUXDOWN_EMBED_WEBROOT") {
        Some(v) => manifest_dir.join(v),
        None => manifest_dir.join("../../web/dist"),
    };
    println!("cargo::rerun-if-changed={}", webroot.display());

    let mut files = BTreeMap::new();
    if webroot.is_dir() {
        collect(&webroot, "", &mut files);
    }
    if files.is_empty() {
        println!(
            "cargo::warning=Web UI not embedded: {} is missing or empty (run `bun run build` in web/, or set FLUXDOWN_EMBED_WEBROOT)",
            webroot.display()
        );
    } else if !files.contains_key("index.html") {
        println!(
            "cargo::warning=Web UI embedded without index.html: {} is not a Vite build output",
            webroot.display()
        );
    }

    let mut code = String::from("// @generated by native/agent/build.rs — do not edit.\n");
    code.push_str("pub(crate) static EMBEDDED_ASSETS: &[EmbeddedAsset] = &[\n");
    for (rel, abs) in &files {
        println!("cargo::rerun-if-changed={}", abs.display());
        let bytes = match std::fs::read(abs) {
            Ok(b) => b,
            Err(e) => panic!("failed to read {}: {e}", abs.display()),
        };
        writeln!(
            code,
            "    EmbeddedAsset {{ path: {rel:?}, bytes: include_bytes!({path:?}), content_type: {ct:?}, etag: {etag:?} }},",
            path = abs.to_string_lossy(),
            ct = content_type(rel).unwrap_or_else(|| {
                // 兜底而非拒收：文件照嵌不误，但把「新资产类型没登记」这件事
                // 摆到构建输出里，避免它以错误 Content-Type 静默上线。
                println!(
                    "cargo::warning=embedded asset `{rel}` has no Content-Type mapping, serving as application/octet-stream (add its extension to content_type() in native/agent/build.rs)"
                );
                "application/octet-stream"
            }),
            etag = etag(&bytes),
        ).unwrap_or_else(|error| panic!("writing embedded asset metadata into a String failed: {error}"));
    }
    code.push_str("];\n");

    // 内容不变则不落盘：生成文件的 mtime 一动，rustc 就要重编整个 crate。
    let dest = out_dir.join("web_assets.rs");
    if std::fs::read_to_string(&dest).is_ok_and(|old| old == code) {
        return;
    }
    if let Err(e) = std::fs::write(&dest, &code) {
        panic!("failed to write {}: {e}", dest.display());
    }
}

/// 递归收集 `dir` 下全部文件，键为 URL 路径（`/` 分隔，不含前导斜杠）。
fn collect(dir: &Path, prefix: &str, out: &mut BTreeMap<String, PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(it) => it,
        Err(e) => panic!("failed to read dir {}: {e}", dir.display()),
    };
    for entry in entries.flatten() {
        let path = entry.path();
        // 非 UTF-8 文件名无法映射为 URL 路径，跳过而不是让整个构建失败。
        let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
            println!(
                "cargo::warning=skipping non-UTF-8 asset name: {}",
                path.display()
            );
            continue;
        };
        let rel = if prefix.is_empty() {
            name
        } else {
            format!("{prefix}/{name}")
        };
        if path.is_dir() {
            collect(&path, &rel, out);
        } else {
            out.insert(rel, path);
        }
    }
}

/// 强 ETag：FNV-1a 64 内容哈希 + 长度。字节一致即命中 304，无需 mtime
/// （嵌入资源没有 mtime 可言）。
fn etag(bytes: &[u8]) -> String {
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for b in bytes {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("\"{hash:016x}-{:x}\"", bytes.len())
}

/// 扩展名 → Content-Type。**这张表不是准入门槛**：`collect` 收什么就嵌什么，
/// 表只决定响应头；返回 `None` 表示没登记，调用方会打 warning 并按
/// `application/octet-stream` 兜底（照样嵌入、照样能取，只是浏览器不解析）。
/// 覆盖面按「Vite/Rollup 及其插件生态实际会吐出的产物」取，新类型加一行即可。
fn content_type(rel: &str) -> Option<&'static str> {
    let ext = Path::new(rel)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();
    let ct = match ext.as_str() {
        "html" | "htm" | "xhtml" => "text/html; charset=utf-8",
        "js" | "mjs" | "cjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "webmanifest" => "application/manifest+json; charset=utf-8",
        "xml" => "application/xml; charset=utf-8",
        "txt" | "md" => "text/plain; charset=utf-8",
        "csv" => "text/csv; charset=utf-8",
        "vtt" => "text/vtt; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" | "apng" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "bmp" => "image/bmp",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "eot" => "application/vnd.ms-fontobject",
        "wasm" => "application/wasm",
        "mp4" | "m4v" => "video/mp4",
        "webm" => "video/webm",
        "mp3" => "audio/mpeg",
        "m4a" => "audio/mp4",
        "ogg" | "oga" => "audio/ogg",
        "wav" => "audio/wav",
        "glb" => "model/gltf-binary",
        "gltf" => "model/gltf+json",
        "pdf" => "application/pdf",
        "zip" => "application/zip",
        _ => return None,
    };
    Some(ct)
}
